### ISSUE TITLE
The all badges script seems to be patched. (or just for me)

### ISSUE THREAD

**Issue by TomWSC828** [hxr404/Discord-Console-hacks#12]
![image](https://user-images.githubusercontent.com/67176819/126862257-5c080dcb-e6ca-493b-91a0-6c67650b64a5.png)
I'm too shock to say anything

**Comment by TomWSC828** [comment]
btw, funny thing that other users DO see the badge

**Comment by steinhorror** [comment]
The Error here is not from the code, you can tell by the -1 response. And it works for me.

**Comment by hxr404** [comment]
yeah, the errors below the -1 are unrelated.


> btw, funny thing that other users DO see the badge.

thats probably just because the cache didn't refresh after switching accounts

**Comment by hxr404** [comment]
if there's still an issue, you can always reopen this

**Comment by TomWSC828** [comment]
nah, it's just me being stupid

**Comment by TomWSC828** [comment]
but thanks!
