### ISSUE TITLE
Big issue

### ISSUE THREAD

**Issue by BraketsHasGithub** [hxr404/Discord-Console-hacks#19]
VM431:1 Uncaught ReferenceError: webpackJsonp is not defined
    at <anonymous>:1:125
    at <anonymous>:1:922
trying to use staff mode and the same on all badges except its only on 1:15

**Comment by hxr404** [comment]
#17 fixes this
I currently don't have access to my dev machine (with git on it) but I'll merge the PR asap
In the meantime try using the fork

**Comment by hxr404** [comment]
Feel free to reopen in case theres still an issue left
