### ISSUE TITLE
Issue with Token Login Script

### ISSUE THREAD

**Issue by mariosva** [hxr404/Discord-Console-hacks#4]
doesnt work for me

**Comment by mariosva** [comment]
![slika](https://user-images.githubusercontent.com/86047692/122366938-4feff980-cf5c-11eb-999d-9585f612d8fb.png)

**Comment by mariosva** [comment]
after i pasted that script twice it just takes me to discord home page

**Comment by hxr404** [comment]
Do you mean the token login script?

**Comment by hxr404** [comment]
@mariosva Do you still have problems with the script?
The Screenshot you provided doesn't even show the output of the script,
that error message is a spotify error wich is caused by Discord and its normal.

So please provide a full screenshot or a video

Alternatively join the [Discord Server](https://discord.gg/T7T3svK3rf) and we can resolve your problems via DM's

**Comment by DarkRabbit-0** [comment]
if still having issues try using ->
get user token ->
```bash
Object.values(webpackJsonp.push([
    [], {
        ['']: (_, e, r) => {
            e.cache = r.c
        }
    },
    [
        ['']
    ]
]).cache).find(m => m.exports && m.exports.default && m.exports.default.getToken !== void 0).exports.default.getToken()
```
logout of your account and -> 

```bash
function login(token) {
    setInterval(() => {
        document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = `"${token}"`;
    }, 100);
    setTimeout(() => {
        location.reload();
    }, 2500);
}
login("Token u copyied");
```

**Comment by mariosva** [comment]
https://youtu.be/s4Sb_05NsjU file size is too large so i uploaded the video to yt and copied the link here

**Comment by hxr404** [comment]
> 
> 
> https://youtu.be/s4Sb_05NsjU file size is too large so i uploaded the video to yt and copied the link here

seems like your problem is resolved?

(btw. I do not provide support for third-party scripts, only scripts that are in the main readme)

**Comment by hxr404** [comment]
Well for me it seems like your issue is resolved. I close this for inactivity now.

**Comment by 82n** [comment]
> after i pasted that script twice it just takes me to the discord home page instead of login page where i can use that token
It is due to your token is invalid.
