### ISSUE TITLE
nitro :(

### ISSUE THREAD

**Issue by Xx7sniper7xX** [hxr404/Discord-Console-hacks#42]
no nitro

**Comment by Raz-js** [comment]
There was never a nitro hack, its was a betterdiscord plugin lmaooo

**Comment by hxr404** [comment]
> There was never a nitro hack, its was a betterdiscord plugin lmaooo

that's not true but ok.


> no nitro

@Xx7sniper7xX you are in the wrong repo here. Check out https://github.com/hxr404/Discord-Oxygen
