### ISSUE TITLE
Token diagram

### ISSUE THREAD

**Issue by blooketpls** [hxr404/Discord-Console-hacks#48]
Hi hxr404, I am so excited to see this github project! But my only question is how do u find the token from someone's user like the [diagram](https://user-images.githubusercontent.com/34555296/120932740-4ca47480-c6f7-11eb-9270-6fb3fbbd856c.png)
Pls tell me thanks

**Comment by hxr404** [comment]
I'm not entirely sure whether I understood your question correctly.
If you're asking how to obtain someone's token:
Use the cipy token script
If your question is, how I found the syntax of the token:
Mostly through trying out and also thanks to #2

**Comment by blooketpls** [comment]
i mean how to get someone's dc token?

**Comment by hxr404** [comment]
> i mean how to get someone's dc token?

As I said before, use the token copy script.

**Comment by Anonymous941** [comment]
@hxr404 I think this is a script kiddie who thinks the diagram is some way to calculate someone else's token and hack them.
@blooketpls Sorry, you can't just hack someone's account that easily.  You'll have to convince them to run the token copy script and send it to you.

**Comment by blooketpls** [comment]
Oh,ok. Understand
