### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by l4tt** [hxr404/Discord-Console-hacks#58]
Honestly i discovered the token grab and list of channels id grab, posted it on a repo that was over 3 years old and 100+ stars and it looks like you are using the same method but just adding a copy to clipboard func.

This is the old repo and it had most of the stuff that's on this repo, but my acc sadly got banned.
[](https://github.com/psauxx/discord-js)

all i am asking is you don't claim credit for something you never found in the first place.

the reason i am telling you this is because you claim to have found these "hacking scripts", when we both know it's just clientside cmds.

**Comment by Emayeah** [comment]
:(

**Comment by hxr404** [comment]
> Honestly i discovered the token grab and list of channels id grab, posted it on a repo that was over 3 years old and 100+ stars and it looks like you are using the same method but just adding a copy to clipboard func.
> 
> This is the old repo and it had most of the stuff that's on this repo, but my acc sadly got banned.
> 
> all i am asking is you don't claim credit for something you never found in the first place.
> 
> the reason i am telling you this is because you claim to have found these "hacking scripts", when we both know it's just clientside cmds.

Even though things like that happen often in this community, I can guarantee you I didn't copy any of your code.
3 years ago, the Chunkdiscord_app variable (on which most of the scripts rely on) didn't even exist...

Also, everything these scripts do is interacting with Discords API. It's trivial to discover them on your own, so copying someone else's work wouldn't even make sense. After all, why would someone go through the hassle of looking through other peopel's code while risking a copyright infringement lawsuit if they could simply look at their Browser's Debugger and read discord's code right away
