### ISSUE TITLE
Err 

### ISSUE THREAD

**Issue by rober401** [hxr404/Discord-Console-hacks#6]
First 
uncaught TypeError: Cannot redefine property: isDeveloper
    at Function.defineProperty (<anonymous>)
    at <anonymous>:1:259
    at <anonymous>:1:922 

This is what I get when runner your make mod script?

**Comment by hxr404** [comment]
weird, I can't reproduce that error.
Do you use Discord Web or Desktop?

**Comment by hxr404** [comment]
closed due to inactivity
