### ISSUE TITLE
Enable Badges (locally) does not work anymore

### ISSUE THREAD

**Issue by Aholicknight** [hxr404/Discord-Console-hacks#64]
The command to enabled badges locally (for you only) does not work anymore:
```js
webpackChunkdiscord_app.push([[Math.random()],{},(req)=>{for(const m of Object.keys(req.c).map((x)=>req.c[x].exports).filter((x)=>x)){if(m.default&&m.default.getCurrentUser!==undefined){return m.default.getCurrentUser().flags=99999999999}}}]);
``` 
Is there a way that this can be fixed?

**Comment by Raz-js** [comment]
> #65 solves this problem

There was a way more simpler way to fix this 💀

**Comment by Raz-js** [comment]
Wait it works wym its not working?

**Comment by Aholicknight** [comment]
> Wait it works wym its not working?

Running the command in the issue does not give badges. Run it and see for yourself.

**Comment by watameln** [comment]
![image](https://user-images.githubusercontent.com/90981615/201322467-9ec2a72c-318a-41e6-9dd3-d452df82d749.png)
They have made a new active developer badge and they have fixed the code to give yourself all badges.

**Comment by hxr404** [comment]
hopefully #65 fixed it, if not please reopen / comment.
