### ISSUE TITLE
Token not working

### ISSUE THREAD

**Issue by Brandon981026** [hxr404/Discord-Console-hacks#69]
The token is not working
logger/grabber

**Comment by NuroC** [comment]
Are you getting any errors?

**Comment by RobinRMC** [comment]
funny number

**Comment by Brandon981026** [comment]
YEAh lmao


RobinRMC ***@***.***> 於 2022年12月23日 週五 下午5:56寫道：

**Comment by hxr404** [comment]
@Brandon981026 Please provide more information to your bug report, like Discord Version / Build Type, Logs/Error Messages you're getting etc.

**Comment by hxr404** [comment]
Reopen if you're still having issues (and make sure to include more details)
